name: Checkstyle

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install JDK 15
        uses: actions/setup-java@v1.4.3
        with: 
          java-version: 15
      - name: Run Gradle build
        run: ./gradlew build
